from sqlalchemy import Column, Integer, String, Float, Text, DateTime
from datetime import datetime
from .database import Base

class Discovery(Base):
    """
    Represents a scientific discovery made by the Gemini Agent 
    on a specific coordinate in the JWST Deep Field.
    """
    __tablename__ = "discoveries"

    id = Column(Integer, primary_key=True, index=True)
    target_name = Column(String, index=True)      # e.g., "SMACS 0723"
    ra = Column(Float)                            # Right Ascension
    dec = Column(Float)                           # Declination
    classification = Column(String)               # e.g., "Gravitational Lens", "Merging Galaxy"
    report_text = Column(Text)                    # The full ApJ Markdown memo generated by Gemini
    image_url = Column(String, nullable=True)     # Optional: URL of the cropped object
    created_at = Column(DateTime, default=datetime.utcnow)
